# Generated by Django 5.2.17 on 2026-08-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0004_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
    ]
